// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: attachments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (post_id, file_url, file_name, mime_type, file_size)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, post_id, file_url, file_name, mime_type, file_size, created_at
`

type CreateAttachmentParams struct {
	PostID   uuid.UUID
	FileUrl  string
	FileName sql.NullString
	MimeType sql.NullString
	FileSize sql.NullInt64
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRowContext(ctx, createAttachment,
		arg.PostID,
		arg.FileUrl,
		arg.FileName,
		arg.MimeType,
		arg.FileSize,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.FileUrl,
		&i.FileName,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
	)
	return i, err
}
