// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Attachment struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	FileUrl   string
	FileName  sql.NullString
	MimeType  sql.NullString
	FileSize  sql.NullInt64
	CreatedAt sql.NullTime
}

type Flag struct {
	ID        uuid.UUID
	PostID    uuid.UUID
	UserID    uuid.UUID
	Reason    sql.NullString
	CreatedAt sql.NullTime
}

type Post struct {
	ID        uuid.UUID
	AuthorID  uuid.UUID
	CourseID  string
	Topic     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

type PostVote struct {
	PostID    uuid.UUID
	UserID    uuid.UUID
	CreatedAt sql.NullTime
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID                  uuid.UUID
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Email               string
	HashedPassword      string
	IsVerified          sql.NullBool
	VerificationCode    sql.NullString
	VerificationExpires sql.NullTime
}

type VerificationCode struct {
	ID        int32
	Email     string
	Code      string
	CreatedAt sql.NullTime
	Verified  sql.NullBool
}
