// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: posts.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createPost = `-- name: CreatePost :one
INSERT INTO posts (id, author_id, course_id, topic, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, author_id, course_id, topic, created_at, updated_at
`

type CreatePostParams struct {
	ID        uuid.UUID
	AuthorID  uuid.UUID
	CourseID  string
	Topic     string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, createPost,
		arg.ID,
		arg.AuthorID,
		arg.CourseID,
		arg.Topic,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.CourseID,
		&i.Topic,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
