// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password, is_verified, verification_code, verification_expires)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1, -- email
    $2, -- hashed_password
    FALSE, -- default unverified
    $3, -- verification_code
    $4  -- verification_expires
)
RETURNING id, created_at, updated_at, email, hashed_password, is_verified, verification_code, verification_expires
`

type CreateUserParams struct {
	Email               string
	HashedPassword      string
	VerificationCode    sql.NullString
	VerificationExpires sql.NullTime
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.HashedPassword,
		arg.VerificationCode,
		arg.VerificationExpires,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsVerified,
		&i.VerificationCode,
		&i.VerificationExpires,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, hashed_password, is_verified, verification_code, verification_expires FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
		&i.IsVerified,
		&i.VerificationCode,
		&i.VerificationExpires,
	)
	return i, err
}
