// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: verification.sql

package database

import (
	"context"
)

const getVerificationCode = `-- name: GetVerificationCode :one
SELECT code FROM verification_codes WHERE email = $1
`

func (q *Queries) GetVerificationCode(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, getVerificationCode, email)
	var code string
	err := row.Scan(&code)
	return code, err
}

const insertVerificationCode = `-- name: InsertVerificationCode :exec
INSERT INTO verification_codes (email, code)
VALUES ($1, $2)
ON CONFLICT (email)
DO UPDATE SET code = EXCLUDED.code, verified = FALSE, created_at = NOW()
`

type InsertVerificationCodeParams struct {
	Email string
	Code  string
}

func (q *Queries) InsertVerificationCode(ctx context.Context, arg InsertVerificationCodeParams) error {
	_, err := q.db.ExecContext(ctx, insertVerificationCode, arg.Email, arg.Code)
	return err
}

const markEmailVerified = `-- name: MarkEmailVerified :exec
UPDATE verification_codes SET verified = TRUE WHERE email = $1
`

func (q *Queries) MarkEmailVerified(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, markEmailVerified, email)
	return err
}
