FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o server ./cmd

FROM alpine:3.18

WORKDIR /app
COPY --from=builder /app/server .
COPY .env .

EXPOSE 8080
CMD ["./server"]
